name: Bump version in Dart project

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
      
      BOT_GPG_KEY:
        required: true

    inputs:
      trigger_major:
          description: Whether to add major as target
          required: true
          type: boolean

      trigger_minor:
          description: Whether to add minor as target
          required: true
          type: boolean

      trigger_patch:
          description: Whether to add patch as target
          required: true
          type: boolean

      bump_build:
          description: Whether to bump the build number
          required: true
          type: boolean

      create_tag:
          description: Whether to create a tag with new version
          required: true
          type: boolean

      rebuild_project:
          description: Whether to generate build/source files
          required: true
          type: boolean

      verify_build:
          description: Whether to run test verifying the build
          required: false
          default: false
          type: boolean

      path:
          description: Path to yaml/json file
          required: false
          type: string
          default: 'pubspec.yaml'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      # Configure Commit Signing
      - name: ğŸŒ½ Corn-figure Git ;)
        id: corn-fig-git
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: ğŸ¯ Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: ğŸ” Extract semVer target
        id: extract_target
        uses: ./.github/actions/extract_target
        with:
          major: ${{ inputs.trigger_major }}
          minor: ${{ inputs.trigger_minor }}
          patch: ${{ inputs.trigger_patch }}

      - name: â¬† Bump version
        uses: ./.github/actions/bump_version
        with:
          target: ${{ steps.extract_target.outputs.target }}
          bump-build-number: ${{ inputs.bump_build }}
          path: ${{ inputs.path }}

      - name: ğŸ§¬ Generate build files
        if: ${{ inputs.rebuild_project == true }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: ğŸ” Get version
        id: get_version
        uses: ./.github/actions/extract_version
        with:
          path: ${{ inputs.path }}

      - name: ğŸ†• Commit and Tag
        run: |
          git commit -am "chore: v${{steps.get_version.outputs.version}}"
          git push

          if [["${{ inputs.create_tag }}" == "true"]]; then
              git tag -a ${{steps.get_version.outputs.version}} HEAD -m "v${{steps.get_version.outputs.version}}"
              git push origin ${{steps.get_version.outputs.version}}
          else
              echo "noOp"
          fi;
        env:
          GIT_AUTHOR_NAME: ${{ steps.corn-fig-git.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.corn-fig-git.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.corn-fig-git.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.corn-fig-git.outputs.email }}

      - name: âœ… Verify build
        if: ${{ inputs.verify_build == true }}
        run: |
          git pull
          dart pub get
          dart run test --run-skipped -t version-verify
